installerInfo: '{ "productId": "OnPremObservability-Newrelic/2.0.0", "features": [ { "featureId": "ArtifactoryVersion/{{ default .Chart.AppVersion .Values.artifactory.image.version }}" }, { "featureId": "{{ if .Values.postgresql.enabled }}postgresql{{ else }}{{ .Values.database.type }}{{ end }}/0.0.0" }, { "featureId": "Platform/{{ default "kubernetes" .Values.installer.platform }}" },  { "featureId": "Channel/OnPremObservability-Newrelic-Helm" } ] }'
artifactory:
  customInitContainersBegin: |
    - name: "download-fluentd-conf-on-persistent-volume"
      image: {{ include "artifactory.getImageInfoByValue" (list . "initContainers") }}
      imagePullPolicy: "{{ .Values.artifactory.image.pullPolicy }}"
      command:
        - 'sh'
        - '-c'
        - >
          mkdir -p {{ .Values.artifactory.persistence.mountPath }}/etc/fluentd/;
          curl https://raw.githubusercontent.com/jfrog/log-analytics-newrelic/master/fluent.conf.rt -o {{ .Values.artifactory.persistence.mountPath }}/etc/fluentd/fluentd.conf;
      volumeMounts:
        - mountPath: "{{ .Values.artifactory.persistence.mountPath }}"
          name: artifactory-volume
  customSidecarContainers: |
    - name: "artifactory-fluentd-sidecar"
      image: "releases-pts-observability-fluentd.jfrog.io/fluentd:4.5"
      imagePullPolicy: "IfNotPresent"
      volumeMounts:
        - mountPath: "{{ .Values.artifactory.persistence.mountPath }}"
          name: artifactory-volume
      env:
        - name: JF_PRODUCT_DATA_INTERNAL
          value: {{ .Values.artifactory.persistence.mountPath }}
        - name: JPD_URL
          value: {{ .Values.jfrog.observability.jpd_url }}
        - name: JPD_ADMIN_USERNAME
          value: {{ .Values.jfrog.observability.username }}
        - name: JPD_ADMIN_TOKEN
          valueFrom:
            secretKeyRef:
              name: jfrog-admin-token
              key: token
        - name: COMMON_JPD
          value: {{ .Values.jfrog.observability.common_jpd | quote }}
        - name: NEWRELIC_LICENSE_KEY
          value: {{ .Values.newrelic.license_key }}
        - name: FLUENTD_CONF
          value: ../../../..{{ .Values.artifactory.persistence.mountPath }}/etc/fluentd/fluentd.conf
        - name: NEWRELIC_LOGS_URI
          value: {{ .Values.newrelic.logs_uri }}
        - name: NEWRELIC_METRICS_URI
          value: {{ .Values.newrelic.metrics_uri }}
newrelic:
  license_key: NEWRELIC_LICENSE_KEY
  logs_uri: https://log-api.newrelic.com
  metrics_uri: https://metrics-api.newrelic.com
jfrog:
  observability:
    jpd_url: JPD_URL
    username: JPD_ADMIN_USERNAME
    common_jpd: COMMON_JPD